### ISSUE TITLE
Ground moves even when camera doesn't

### ISSUE THREAD

**Issue by OctarineSourcerer** [OctarineSorcerer/Flower-Prototype#5]
When the camera is limited in its movement, the ground just doesn't care and moves anyway.
Probably need to either have a flag for the safe translation or have the same kinda thing with ground that the camera has.

Probably the first

**Comment by OctarineSorcerer** [comment]
Pretty sure I've fixed this now. The safe translate of the camera will now return a 2D vector stating how much it has *actually* been moved. 
So, when the ground is moving during a movement that may be restricted, instead of moving at its usual speed (speed*deltaTime), it'll move the amount the camera moved
